server:
  port: 8082
spring:
  application:
    name: loans
  datasource:
    url: jdbc:mysql://localhost:3306/loans
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
            ddl-auto: create
    show-sql: true


build:
  version: 2.0