services:
  mysql:
    image: "mysql:8.3.0"
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - mysqlvolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - "kubernetes-network"

networks:
  kubernetes-network:
    external: true

volumes:
  mysqlvolume: